# kubectl -n moneyger create secret generic moneyger-db \
#   --dry-run -o yaml \
#   --from-literal postgres-user=moneyger \
#   --from-literal postgres-password=moneyger \
#   --from-literal postgres-db=moneyger \
#   > moneyger-db-secret.yml
apiVersion: v1
data:
  postgres-db: bW9uZXlnZXI=
  postgres-password: bW9uZXlnZXI=
  postgres-user: bW9uZXlnZXI=
kind: Secret
metadata:
  creationTimestamp: null
  name: moneyger-db
  namespace: moneyger
