apiVersion: v1
kind: Namespace
metadata:
  name: moneyger
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moneyger
  namespace: moneyger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moneyger
  template:
    metadata:
      labels:
        app: moneyger
    spec:
      containers:
      - # image: <image-name>:latest
        # 例: 
        image: making/moneyger:latest
        name: moneyger
        ports:
        - containerPort: 8080
        env:
        - name: _JAVA_OPTIONS
          value: "-Xmx15m -XX:ReservedCodeCacheSize=22M -XX:MaxDirectMemorySize=22M -XX:MaxMetaspaceSize=54M -Xss512K"
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: moneyger-db
              key: postgres-db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: moneyger-db
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: moneyger-db
              key: postgres-password
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@moneyger-db.moneyger.svc.cluster.local:5432/$(POSTGRES_DB)"
        resources:
          limits:
            memory: "128Mi"
          requests:
            memory: "128Mi"
        readinessProbe:
          httpGet:
            path: /expenditures
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /expenditures
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 1
---
kind: Service
apiVersion: v1
metadata:
  name: moneyger
  namespace: moneyger
spec:
  type: LoadBalancer
  selector:
    app: moneyger
  ports:
  - protocol: TCP
    port: 8080
